"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var arquero_1 = require("./arquero");
var luchador_1 = require("./luchador");
var mago_1 = require("./mago");
var arquero = new arquero_1.Arquero("Legolas", 150, 50);
console.log(arquero);
arquero.atacar();
arquero.defender();
arquero.subirDeNivel();
console.log("La vida luego despu\u00E9s de ser atacado es ".concat(arquero.getPuntosDeVida()));
var arqueroEvolucionado = new arquero_1.Arquero("Robin H", 300, 100);
console.log(arqueroEvolucionado);
arqueroEvolucionado.atacar();
arqueroEvolucionado.defender();
arqueroEvolucionado.subirDeNivel();
console.log("La vida luego despu\u00E9s de ser atacado es ".concat(arqueroEvolucionado.getPuntosDeVida()));
var luchador = new luchador_1.Luchador("Aquiles", 200, 90);
console.log(luchador);
luchador.atacar();
luchador.defender();
luchador.subirDeNivel;
console.log("La vida luego despu\u00E9s de ser atacado es ".concat(luchador.getPuntosDeVida()));
var luchadorEvolucionado = new luchador_1.Luchador("Hercules", 400, 180);
console.log(luchadorEvolucionado);
luchadorEvolucionado.atacar();
luchadorEvolucionado.defender();
luchadorEvolucionado.subirDeNivel;
console.log("La vida luego despu\u00E9s de ser atacado es ".concat(luchadorEvolucionado.getPuntosDeVida()));
var mago = new mago_1.Mago("Gandalf", 100, 40);
console.log(mago);
mago.atacar();
mago.defender();
mago.subirDeNivel;
console.log("La vida luego despu\u00E9s de ser atacado es ".concat(mago.getPuntosDeVida()));
var magoEvolucionado = new mago_1.Mago("Merli", 200, 100);
console.log(magoEvolucionado);
magoEvolucionado.atacar();
magoEvolucionado.defender();
magoEvolucionado.subirDeNivel;
console.log("La vida luego despu\u00E9s de ser atacado es ".concat(magoEvolucionado.getPuntosDeVida()));
